Updated to run to wait for job to complete

diff --git a/templates/aml-cli-v2/run-pipeline.yml b/templates/aml-cli-v2/run-pipeline.yml
--- a/templates/aml-cli-v2/run-pipeline.yml
+++ b/templates/aml-cli-v2/run-pipeline.yml
@@ -8,4 +8,28 @@ steps:
       workingDirectory: '$(System.DefaultWorkingDirectory)/data-science-regression'
       scriptLocation: inlineScript
       inlineScript: |
-        az ml job create --file pipeline.yml
+        run_id=$(az ml job create -f pipeline.yml --query name -o tsv)
+        if [[ -z "$run_id" ]]
+        then
+          echo "Job creation failed"
+          exit 3
+        fi
+        az ml job show -n $run_id --web
+        status=$(az ml job show -n $run_id --query status -o tsv)
+        if [[ -z "$status" ]]
+        then
+          echo "Status query failed"
+          exit 4
+        fi
+        running=("Queued" "Starting" "Preparing" "Running" "Finalizing")
+        while [[ ${running[*]} =~ $status ]]
+        do
+          sleep 15 
+          status=$(az ml job show -n $run_id --query status -o tsv)
+          echo $status
+        done
+        if [[ "$status" = "Failed" ]]  
+        then
+          echo "Training Job failed"
+          exit 3
+        fi
