GHA should wait on Azure ML pipeline completion

diff --git a/.github/workflows/run-pipeline.yml b/.github/workflows/run-pipeline.yml
--- a/.github/workflows/run-pipeline.yml
+++ b/.github/workflows/run-pipeline.yml
@@ -35,5 +35,29 @@ jobs:
         run: az extension update -n ml
       - name: run-ml-pipeline
         run: |
-          az ml job create --file ${{ github.workspace }}/${{ inputs.parameters-file  }} --resource-group ${{ inputs.resource_group }} \
-          --workspace-name ${{ inputs.workspace_name }} --query name -o tsv
+          run_id=$(az ml job create --file ${{ github.workspace }}/${{ inputs.parameters-file  }} --resource-group ${{ inputs.resource_group }} \
+          --workspace-name ${{ inputs.workspace_name }} --query name -o tsv)
+          if [[ -z "$run_id" ]]
+          then
+            echo "Job creation failed"
+            exit 3
+          fi
+          az ml job show -n $run_id --web
+          status=$(az ml job show -n $run_id --query status -o tsv)
+          if [[ -z "$status" ]]
+          then
+            echo "Status query failed"
+            exit 4
+          fi
+          running=("NotStarted" "Queued" "Starting" "Preparing" "Running" "Finalizing" "CancelRequested")
+          while [[ ${running[*]} =~ $status ]]
+          do
+            sleep 15 
+            status=$(az ml job show -n $run_id --query status -o tsv)
+            echo $status
+          done
+          if [[ "$status" != "Completed" ]]  
+          then
+            echo "Training Job failed or canceled"
+            exit 3
+          fi
